webapp/news/models.py
from webapp.db import db

class News(db.Model): #Заполняет поля в БД для ссылок новостей
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return '<News {} {}>'.format(self.title, self.url)

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.db import db

class User(db.Model, UserMixin): #Заполняет поля для БД для юзера пароль UserMixin определяет актив 
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)#Зашифровывает пароль функцией

    def check_password(self, password):# Принимает зашифрованый пароль из БД и строку переданную пользователем
        return check_password_hash(self.password, password)#Нужно вернуть тру или фаллс чтобы понят ьверный пароль или нет

    @property    
    def is_admin(self): #проверка на админа 
        return self.role == 'admin'

    def __repr__(self):
        return '<User name = {} id ={}'.format(self.username, self.id)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField, HiddenField, SelectField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    team_list = ['Team1', 'Team2', 'Team3', 'Team4']
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "form-check-input"})#галочка дял запоминания пользователя
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-primary"})

webapp/__init__.py
from flask import Flask, render_template#flash - позволяет передавать сообщения между route-ами rederict- делает перенаправление со страницы на страницу url; - позволяет получить юрл 
from flask_login import LoginManager, current_user, login_required #менеджер логина? кароче дял работы с логином



from webapp.db import db
from webapp.admin.views import blueprint as admin_blueprint
from webapp.user.views import blueprint as user_blueprint
from webapp.user.models import User
from webapp.news.views import blueprint as news_blueprint
from webapp.news.models import News


#ЗАПУСК сервера set FLASK_APP=webapp && set FLASK_ENV=development && set FLASK_DEBUG=1 && flask run


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)#делаем инит?

    login_manager = LoginManager() #создаем экземпляр логи менеджера(почти как в model db = SQLalchemy)
    login_manager.init_app(app)#
    login_manager.login_view = 'user.login'# название функции login

    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader#при заходе на страницу будет делать запрос в бд по ИД
    def load_user(user_id):
        return User.query.get(user_id)# возвращает юзера по айди 
  
       
    return app

webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required #проверяет если пользователь не аутоинтефицирован то выдана ошибка и перебрасывает на логин
def admin_index():
    title = "Панель управления"
    return render_template('admin/index.html', page_title = title)

webapp/news/views.py
from flask import Blueprint, current_app, render_template

from webapp.news.models import News
from webapp.weather import weather_city

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():#Функция для отображения новостей
    title = 'Новости Python'#заголовок
    weather = weather_city(current_app.config['WEATHER_DEFAULT_CITY'])# опредение погоды в выбранном городе из config
    news_list = News.query.order_by(News.published.desc()).all()#доставание query из БД списка новостей
    return render_template('news/index.html', page_title = title, weather = weather, news_list = news_list) # передача в index.html нужных параметров

webapp/user/views.py
from flask import Blueprint, render_template, flash, redirect, url_for #flash - позволяет передавать сообщения между route-ами rederict- делает перенаправление со страницы на страницу url; - позволяет получить юрл 
from flask_login import current_user, login_user, logout_user #менеджер логина? кароче дял работы с логином

from webapp.user.forms import LoginForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():#функция авторизации
    if current_user.is_authenticated:#Проверка на аутотифенкацию ( чтобы при обновлении юзер не пропадал)
        return redirect(url_for('news.index'))
    title = "Авторизация"
    login_form = LoginForm()# из webapp.forms экземпляр формы
    return render_template('user/login.html', page_title=title, form=login_form)# так же передача в login.html

@blueprint.route('/process-login', methods=['POST'])#какие методы обрабатывает роут(т.к. мы хотим обработать POST) /process-login'
def process_login():
    form = LoginForm()#экземпляр формы
    if form.validate_on_submit(): #форма валидируется ( проверяте на ошибки ( заполнены ли поля и тд))
        user = User.query.filter_by(username=form.username.data).first()#запрашиваем из бд данные юзернейма ИЗ БД БЕРЕТСЯ ПЕРЕМЕННАЯ
        if user and user.check_password(form.password.data): #проверка на существование пользователя и проверка пароля                
            login_user(user, remember=form.remember_me.data)#запоминание пользователя
            login_user(user)#заолгинили пользователя
            flash('Вы вошли на сайт')
            return redirect(url_for('news.index'))#перекидываем на странциу индекс

    flash('Неправильное имя пользователя или пароль')#если не прошло
    return redirect(url_for('user.login')) #возвращаем на страницу логина  
@blueprint.route('/logout')#возможность выйти из пользователя
def logout():
    logout_user()#разлогинивание
    flash('вы успешно разлогинились')#алерт через флэш в хтмл
    return redirect(url_for('news.index')) #перенаправление на другую страницу

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
      {% include 'menu.html' %}
    <div class="container">
        <h1>{{ page_title }}</h1>      
        {% block content %}{% endblock %}
    </div>
   

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Главная страница <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
        </li>        
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
      </form>
    </div>
  </nav>

webapp/templates/news/index.html
{% extends "base.html" %}
 
{% block content %}
  <div class="row">        
      <div class="col-8">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
            </div>
          {% endif %}
        {% endwith %}
        <h2>Новости</h2>
        {% for news in news_list %}
        <h3><a href = '{{ news.url }}'>{{ news.title }}</a></h3>
        <p>{{ news.published.strftime('%d.%m.%Y')}}</p>
        <hr />              
        {% endfor %}
      </div>
      <div class="col-4">
          <h2>Прогноз погоды</h2>
          {% if weather %}
              Температура {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
          {% else %}
              Сервис погоды недоступен
          {% endif %}

      </div>      

  </div>
{% endblock %}   

webapp/templates/user/login.html
{% extends "base.html" %}
 
{% block content %}
    <div class="row">        
        <div class="col-4">
          {% with messages = get_flashed_messages() %}<!-- Вывод алерта если он присутствует? -->
            {% if messages %}
              <div class="alert alert-warning" role="alert">
                      {% for message in messages %}
                          {{ message }}<br>
                      {% endfor %}
              </div>
            {% endif %}
          {% endwith %}
          <form action="{{ url_for('user.process_login') }}" method="POST"> <!-- вывод url -->
            {{ form.hidden_tag() }}
            <div class = "form-group">
              {{ form.username.label }}<br>
              {{ form.username() }}
            </div>              
            <div class = "form-group">
              {{ form.password.label }}<br>
              {{ form.password() }}
            </div>            
            <div class="form-group form-check">
              {{ form.remember_me() }}
              {{ form.remember_me.label(class_='form-check-label') }}
            </div>
          {{ form.submit() }}
          
          </form>
        </div>
        <div class="col-4">
            
        </div>      
    </div>
{% endblock %}  
    